# Test Image
FROM node:lts-alpine as builder
LABEL maintainer "ard@gmail.com"

ENV NODE_ENV=testing

WORKDIR /app
COPY package.json pnpm-lock.yaml ./

RUN set -x && pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

# Production Image
FROM node:lts-alpine as main
LABEL maintainer "ard@gmail.com"

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app
EXPOSE 3000

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/dist ./dist
RUN touch .env

RUN set -x && pnpm install --frozen-lockfile --prod

CMD ["pnpm", "start:prod"]
